
spring:
  mail:
    host: smtp.gmail.com
    username: aliadesh631@gmail.com
    password: kdwqvsityiiigcmq
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true